---
title: "punto2-tp05.03-reglasAsociacion"
author: "juan-natello"
date: "22/11/2020"
output: html_document
---

```{r setup, include=FALSE}
library(arules)

data("Groceries")
```

```{r setup, include=FALSE}
reglas <- apriori(Groceries, parameter = list(support=0.01, confidence=0.01, target = "rules"))
# print(reglas)
# inspect(reglas)

reglas <- sort(reglas, by="lift", decreasing=TRUE)
inspect(head(reglas, n = 4, by = "lift"))
```



```{r}

rules = apriori(Groceries, parameter = list(support = 0.09, confidence = 0.1))
rules <- sort(rules, by="support", decreasing=TRUE)
summary(rules)
inspect(rules)
# path_file = "code/punto-2/resultado.inspect.csv"
# write.csv(x = resultado.inspect, file = path_file , row.names = FALSE) 


```


```{r}

reglas_water <- apriori(Groceries, parameter = list(support=0.01, confidence=0.01, target = "rules"), appearance = list(rhs="bottled water"))
inspect(reglas_water)
inspect(sort(reglas_water,by="lift",decreasing=TRUE))
```


```{r}

reglas_beer <- apriori(Groceries, parameter = list(support=0.01, confidence=0.01, target = "rules"), appearance = list(rhs="bottled beer"))
inspect(reglas_beer)
inspect(sort(reglas_beer,by="lift",decreasing=TRUE))

```



```{r}
library(RColorBrewer)
# itemFrequencyPlot(Groceries, topN = 20,  
#                           col = brewer.pal(8, 'Pastel2'), 
#                           main = 'Relative Item Frequency Plot', 
#                           type = "relative", 
#                           ylab = "Item Frequency (Relative)")```

itemFrequencyPlot(Groceries,
                topN = 10, 
                col = brewer.pal(8, 'Pastel2'),
                support = 0.01, 
                cex.names=0.8, 
                main="MinSup=0.01")
```

