---
title: "punto2-tp05.03-reglasAsociacion"
author: "juan-natello"
date: "22/11/2020"
output: html_document
---

```{r setup, include=FALSE}
library(arules)

```





```{r}


bank_portugal = "~/UNLu/BasedeDatosMasivas/Trabajos Practicos/Tp05.03ReglasDeAsociacion-R/code/punto-3/bank-full.csv"

bnk_port = read.csv(bank_portugal, sep = ";", header = TRUE)

# Exploramos y discretizamos (a ojo)
bnk_port.age = discretize(bnk_port$age, method = "fixed", breaks = c(-Inf, 35, 48, 60, Inf), labels = c("joven", "adulto", "mediana_edad", "tercera_edad"))

bnk_port.balance = discretize(bnk_port$balance, method = "fixed", breaks = c(-Inf, 0, 500, 20000, 50000, Inf), labels = c("muy malo", "sin perdida", "poca ganancia", "hubo ganancia","mucha ganancia"))

bnk_port.duration = discretize(bnk_port$duration, method = "fixed", breaks = c(-Inf, 500, 1000, 2000, Inf), labels = c("poco tiempo", "tiempo moderado", "bastante tiempo", "tiempo excedido"))

bnk_port.campaign = discretize(bnk_port$campaign, method = "fixed", breaks = c(-Inf, 10, 20, Inf), labels = c("pocas veces", "bastantes veces", "demasiadas veces"))

bnk_port.pdays = discretize(bnk_port$pdays, method = "fixed", breaks = c(-Inf, 0, 200, 500, Inf), labels = c("no aplica", "poco tiempo", "mucho tiempo", "demasiadas tiempo"))

bnk_port.previous = discretize(bnk_port$previous, method = "fixed", breaks = c(-Inf, 0, 9, 39, 79, Inf), labels = c("ninguna vez", "casi nada", "algunas veces", "muchas veces", "demasiadas veces"))


bnk_port.day = discretize(bnk_port$day, method = "fixed", breaks = c(-Inf, 10, 20, Inf), labels = c("principio de mes", "mitad de mes", "fin de mes"))


bnk_port_discretizado = data.frame(as.factor(bnk_port.age), 
                               as.factor(bnk_port$job), 
                               as.factor(bnk_port$marital), 
                               as.factor(bnk_port$education), 
                               as.factor(bnk_port$default), 
                               as.factor(bnk_port.balance), 
                               as.factor(bnk_port$housing), 
                               as.factor(bnk_port$loan), 
                               as.factor(bnk_port$contact), 
                               as.factor(bnk_port.day),
                               as.factor(bnk_port$month),
                               as.factor(bnk_port.duration), 
                               as.factor(bnk_port.campaign), 
                               as.factor(bnk_port.pdays),
                               as.factor(bnk_port.previous),
                               as.factor(bnk_port$poutcome),
                               as.factor(bnk_port$y)
                               )
names(bnk_port_discretizado) = c("bnk_port.age", 
                             "bnk_port.job", 
                             "bnk_port.marital", 
                             "bnk_port.education", 
                             "bnk_port.default", 
                             "bnk_port.balance", 
                             "bnk_port.housing", 
                             "bnk_port.loan", 
                             "bnk_port.contact", 
                             "bnk_port.day", 
                             "bnk_port.month", 
                             "bnk_port.duration", 
                             "bnk_port.campaign", 
                             "bnk_port.pdays", 
                             "bnk_port.previous", 
                             "bnk_port.poutcome", 
                             "bnk_port.y" 
                             )
View(bnk_port_discretizado)
```

```{r}
# library(arules)
# library(RColorBrewer)


bnk_port_transacciones <- as(bnk_port_discretizado, "transactions")
# inspect(bnk_port_transacciones[1:4])
bnk_port_rules = apriori(bnk_port_transacciones, parameter = list(support=0.01, confidence=0.01, target = "rules"), appearance = list(rhs="bnk_port.y=yes"))

summary(bnk_port_rules)

inspect(head(sort(bnk_port_rules, by="lift", decreasing = TRUE),30))
# View(bnk_port_rules)

itemFrequencyPlot(bnk_port_transacciones,
                topN = 20, 
                col = brewer.pal(8, 'Pastel2'),
                support = 0.01, 
                cex.names=0.8, 
                main="MinSup=0.01")
```

```{r}
install.packages("arules", dependencies = TRUE)
library(arules)


```

```{r}
bnk_portugal_transacciones = read.transactions(bank_portugal, sep = ";", header = TRUE)



```

```{r}
library(RColorBrewer) 


bank_portugal_df = bnk_port

# inspect(head(bnk_portugal_transacciones))
hist(bank_portugal_df$age, xlim=c(0,100), col = brewer.pal(12, 'Set3'))
hist(bank_portugal_df$balance, xlim = c(-1,2000), col = brewer.pal(8, 'Pastel2'))
hist(bank_portugal_df$duration, xlim=c(0,2000), col = brewer.pal(12, 'Paired'))
hist(bank_portugal_df$campaign, xlim = c(0,25), col = brewer.pal(9, 'Set1'))
hist(bank_portugal_df$pdays, xlim = c(-1,400), col = brewer.pal(8, 'Accent'))

summary(bank_portugal_df$campaign)
summary(bank_portugal_df$duration)
```

```{r}

data <- {}
transactions <- as(as.data.frame(apply(data, 2, as.factor)), "transactions")
rules = apriori(transactions, parameter=list(target="rules", confidence=0.25, support=0.2))

```


```{r}

str(Groceries)

```



```{r}
inspect(Groceries)
```



```{r}


reglas <- apriori(Groceries, parameter = list(support=0.2, confidence=0.2, target = "rules"))

inspect(reglas)

inspect(sort(reglas, by="lift", decreasing = TRUE))

```